name: fapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  pie_chart: ^5.0.0
  flutter_launcher_icons: ^0.13.1


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  
